version: '3.5'
services:
  keepalived:
    environment:
      - VIRTUAL_IP=172.16.197.250
      - VIRTUAL_MASK=24
      - CHECK_IP=any
      - CHECK_PORT=80
      - VRID=150
      - INTERFACE=eth0
    tty: true
    stdin_open: true
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
