FROM debian:buster-slim

COPY Dockerfile.debian /Dockerfile
COPY .bashrc /root/.bashrc

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        keepalived \
        iproute2 \
        tcpdump \
    && rm -rf /var/lib/apt/lists/* /tmp/*

COPY keepalived.sh /usr/bin/keepalived.sh
COPY keepalived.conf /etc/keepalived/keepalived.conf

RUN chmod +x /usr/bin/keepalived.sh; chown root:root /usr/bin/keepalived.sh

ENTRYPOINT ["/usr/bin/keepalived.sh"]
